### ISSUE TITLE
"failed to load the default resource bundle" in restricted Docker containers

### ISSUE THREAD

**Issue by winstxnhdw** [tectonic-typesetting/tectonic#1061]
I get the following error in my Docker server.

```rs
thread 'tokio-runtime-worker' panicked at 'Unable to convert LaTeX to PDF: Error(Msg("failed to load the default resource bundle"), State { next_error: Some(Error(NewStyle(Permission denied (os error 13)
```

This is not exactly an issue with Tectonic as it works fine on my local machine. However, on my Docker server, I usually have to manually set the file permissions of certain directories that my app uses. It would be helpful if anyone knows what directory Tectonic is reading and writing to so that I can give it the appropriate permissions.

Full stack trace:

```rs
Caused by:
    Permission denied (os error 13)), State { next_error: None, backtrace: InternalBacktrace { backtrace: Some(   0: error_chain::backtrace::imp::InternalBacktrace::new
   1: <error_chain::State as core::default::Default>::default
   2: tectonic::config::PersistentConfig::make_cached_url_provider
   3: tectonic::config::PersistentConfig::default_bundle
   4: tectonic::latex_to_pdf
   5: <F as axum::handler::Handler<(M,T1),S,B>>::call::{{closure}}
   6: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
   7: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
   8: <tower::util::map_response::MapResponseFuture<F,N> as core::future::future::Future>::poll
   9: <tower::util::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll
  10: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_inner
  11: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_catch
  12: <hyper::server::conn::upgrades::UpgradeableConnection<I,S,E> as core::future::future::Future>::poll
  13: <hyper::server::server::new_svc::NewSvcTask<I,N,S,E,W> as core::future::future::Future>::poll
  14: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  15: tokio::runtime::task::core::Core<T,S>::poll
  16: tokio::runtime::task::raw::poll
  17: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  18: tokio::runtime::scheduler::multi_thread::worker::Context::run
  19: tokio::runtime::context::scoped::Scoped<T>::set
  20: tokio::runtime::context::runtime::enter_runtime
  21: tokio::runtime::scheduler::multi_thread::worker::run
  22: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  23: tokio::runtime::task::core::Core<T,S>::poll
  24: tokio::runtime::task::harness::Harness<T,S>::poll
  25: tokio::runtime::blocking::pool::Inner::run
  26: std::sys_common::backtrace::__rust_begin_short_backtrace
  27: core::ops::function::FnOnce::call_once{{vtable.shim}}
  28: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1973:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1973:9
      std::sys::unix::thread::Thread::new::thread_start
             at rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys/unix/thread.rs:108:17
  29: start_thread
  30: clone
) } })), backtrace: InternalBacktrace { backtrace: Some(   0: error_chain::backtrace::imp::InternalBacktrace::new
   1: <error_chain::State as core::default::Default>::default
   2: tectonic::config::PersistentConfig::make_cached_url_provider
   3: tectonic::config::PersistentConfig::default_bundle
   4: tectonic::latex_to_pdf
   5: <F as axum::handler::Handler<(M,T1),S,B>>::call::{{closure}}
   6: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
   7: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
   8: <tower::util::map_response::MapResponseFuture<F,N> as core::future::future::Future>::poll
   9: <tower::util::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll
  10: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_inner
  11: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_catch
  12: <hyper::server::conn::upgrades::UpgradeableConnection<I,S,E> as core::future::future::Future>::poll
  13: <hyper::server::server::new_svc::NewSvcTask<I,N,S,E,W> as core::future::future::Future>::poll
  14: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  15: tokio::runtime::task::core::Core<T,S>::poll
  16: tokio::runtime::task::raw::poll
  17: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  18: tokio::runtime::scheduler::multi_thread::worker::Context::run
  19: tokio::runtime::context::scoped::Scoped<T>::set
  20: tokio::runtime::context::runtime::enter_runtime
  21: tokio::runtime::scheduler::multi_thread::worker::run
  22: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  23: tokio::runtime::task::core::Core<T,S>::poll
  24: tokio::runtime::task::harness::Harness<T,S>::poll
  25: tokio::runtime::blocking::pool::Inner::run
  26: std::sys_common::backtrace::__rust_begin_short_backtrace
  27: core::ops::function::FnOnce::call_once{{vtable.shim}}
  28: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1973:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1973:9
      std::sys::unix::thread::Thread::new::thread_start
             at rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys/unix/thread.rs:108:17
  29: start_thread
  30: clone
) } })', src/compile.rs:18:43
stack backtrace:
   0:     0x5632eabd156a - std::backtrace_rs::backtrace::libunwind::trace::h9a6b80bbf328ba5d
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x5632eabd156a - std::backtrace_rs::backtrace::trace_unsynchronized::hd162ec543a11886b
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5632eabd156a - std::sys_common::backtrace::_print_fmt::h78a5099be12f51a6
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x5632eabd156a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha1c5390454d74f71
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x5632eabfbf1f - core::fmt::write::h9ffde816c577717b
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/fmt/mod.rs:1254:17
   5:     0x5632eabcd565 - std::io::Write::write_fmt::h88186074961638e4
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/io/mod.rs:1698:15
   6:     0x5632eabd1335 - std::sys_common::backtrace::_print::h184198273ed08d59
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x5632eabd1335 - std::sys_common::backtrace::print::h1b4d8e7add699453
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x5632eabd29de - std::panicking::default_hook::{{closure}}::h393bcea75423915a
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:269:22
   9:     0x5632eabd2785 - std::panicking::default_hook::h48c64f31d8b3fd03
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:288:9
  10:     0x5632eabd2f3e - std::panicking::rust_panic_with_hook::hafdc493a79370062
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:691:13
  11:     0x5632eabd2e39 - std::panicking::begin_panic_handler::{{closure}}::h0a64bc82e36bedc7
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:582:13
  12:     0x5632eabd19d6 - std::sys_common::backtrace::__rust_end_short_backtrace::hc203444fb7416a16
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:150:18
  13:     0x5632eabd2b92 - rust_begin_unwind
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
  14:     0x5632ea442f63 - core::panicking::panic_fmt::h0f6ef0178afce4f2
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
  15:     0x5632ea443413 - core::result::unwrap_failed::h8090202169109f9c
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/result.rs:1687:5
  16:     0x5632ea4852c5 - <F as axum::handler::Handler<(M,T1),S,B>>::call::{{closure}}::hd1ac3941e6ad8ac0
  17:     0x5632ea4676f4 - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::h4b970cc16c98c70d
  18:     0x5632ea467aa0 - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::h9659b1637742fcff
  19:     0x5632ea45f3b9 - <tower::util::map_response::MapResponseFuture<F,N> as core::future::future::Future>::poll::hd5ed4ba2c2dc07fc
  20:     0x5632ea4858b6 - <tower::util::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll::h1fa93a0d02efaef9
  21:     0x5632ea4a883e - hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_inner::h4003a5ba80c926fe
  22:     0x5632ea4a618c - hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_catch::hac4eb3f993ebec65
  23:     0x5632ea47c2bd - <hyper::server::conn::upgrades::UpgradeableConnection<I,S,E> as core::future::future::Future>::poll::hb766f278e72d1b8f
  24:     0x5632ea4cdb74 - <hyper::server::server::new_svc::NewSvcTask<I,N,S,E,W> as core::future::future::Future>::poll::hcf8d1f953c7e54a0
  25:     0x5632ea4b8ee1 - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::he777ee645af6f72b
  26:     0x5632ea4668b7 - tokio::runtime::task::core::Core<T,S>::poll::hee26d7dba8992613
  27:     0x5632ea4d21e0 - tokio::runtime::task::raw::poll::h99332577c2a0d066
  28:     0x5632eab7b3b2 - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::hc2e2d883e652208b
  29:     0x5632eab7a97c - tokio::runtime::scheduler::multi_thread::worker::Context::run::hca3c50f22408fa9e
  30:     0x5632eab8341a - tokio::runtime::context::scoped::Scoped<T>::set::hd0f0456a69c871b8
  31:     0x5632eab8de42 - tokio::runtime::context::runtime::enter_runtime::hba105dd52d1863b2
  32:     0x5632eab7a2d8 - tokio::runtime::scheduler::multi_thread::worker::run::h8a49d930c1ebe20f
  33:     0x5632eab80df4 - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::hcc9e32be9b4ee614
  34:     0x5632eab83a89 - tokio::runtime::task::core::Core<T,S>::poll::hb21fa4d1eb229748
  35:     0x5632eab7718f - tokio::runtime::task::harness::Harness<T,S>::poll::ha11280a8c79dbe6c
  36:     0x5632eab99866 - tokio::runtime::blocking::pool::Inner::run::h81971dc16dbf684f
  37:     0x5632eab8ea65 - std::sys_common::backtrace::__rust_begin_short_backtrace::h836d878545c6110c
  38:     0x5632eab7cb0f - core::ops::function::FnOnce::call_once{{vtable.shim}}::hdd78228510d2ddd4
  39:     0x5632eabd86b5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::ha1f2224656a778fb
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1973:9
  40:     0x5632eabd86b5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::haa29ed9703f354b7
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1973:9
  41:     0x5632eabd86b5 - std::sys::unix::thread::Thread::new::thread_start::h33b6dae3e3692197
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys/unix/thread.rs:108:17
  42:     0x7fb2f9748ea7 - start_thread
  43:     0x7fb2f951ea2f - clone
  44:                0x0 - <unknown>
```

**Comment by winstxnhdw** [comment]
Tectonic writes to directories in `$XDG_CACHE_HOME/Tectonic/*`

```dockerfile
ENV XDG_CACHE_HOME /cache

RUN mkdir -p /target /cache/Tectonic
RUN chmod 777 /target
RUN chmod -R 777 /cache
```

**Comment by winstxnhdw** [comment]
Sorry for reopening this issue but this problem seems to be back for both `reqwest` and `curl` in `v0.15.0`

```rust
2024-02-25T11:19:49.874085Z ERROR tectonic_api::compile: Failed to compile: failed to load the default resource bundle
2024-02-25T11:20:31.690730Z ERROR tectonic_api::compile: Failed to compile: failed to load the default resource bundle
2024-02-25T11:20:33.841244Z ERROR tectonic_api::compile: Failed to compile: failed to load the default resource bundle
2024-02-25T11:20:35.761226Z ERROR tectonic_api::compile: Failed to compile: failed to load the default resource bundle
2024-02-25T11:20:37.442305Z ERROR tectonic_api::compile: Failed to compile: failed to load the default resource bundle
```
