### ISSUE TITLE
Panic on empty font name

### ISSUE THREAD

**Issue by dm606** [tectonic-typesetting/tectonic#188]
Running tectonic 0.1.8 on
```latex
\documentclass{standalone}
\usepackage{fontspec}
\setmainfont{}

\begin{document}
\end{document}
```
crashes with
```
note: this is a BETA release; ask questions and report bugs at https://tectonic.newton.cx/
Running TeX ...
thread 'main' panicked at 'name must be non-empty', src/io/memory.rs:135:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:206
   3: std::panicking::default_hook
             at libstd/panicking.rs:222
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:400
   5: std::panicking::begin_panic
   6: <tectonic::io::memory::MemoryIo as tectonic::io::IoProvider>::input_open_name
   7: <tectonic::engines::ExecutionState<'a, I>>::input_open_name_format
   8: tectonic::engines::input_open
   9: tt_open_input
  10: read_font_info
  11: new_font
  12: prefixed_command
  13: main_control
  14: tt_run_engine
  15: tex_simple_main
  16: tectonic::engines::tex::TexEngine::process
  17: tectonic::driver::ProcessingSession::tex_pass
  18: tectonic::driver::ProcessingSession::default_pass
  19: tectonic::driver::ProcessingSession::run
  20: tectonic::main
  21: std::rt::lang_start::{{closure}}
  22: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:305
  23: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:101
  24: std::rt::lang_start_internal
             at libstd/panicking.rs:284
             at libstd/panic.rs:361
             at libstd/rt.rs:58
  25: main
  26: __libc_start_main
  27: _start
```

**Comment by pkgw** [comment]
Thanks for reporting! That's definitely a bug.
