### ISSUE TITLE
Rare segfault in `isOpenTypeMathFont`

### ISSUE THREAD

**Issue by Mrmaxmeier** [tectonic-typesetting/tectonic#400]
Xref #397 
Some runs of https://arxiv.org/abs/1702.08766 result in a NULL-deref in `isOpenTypeMathFont`.

Here's a stack trace from one of the core dumps:
```
(gdb) bt
#0  0x00005589e2f7d488 in isOpenTypeMathFont (engine=0x0) at tectonic/xetex-XeTeXLayoutInterface.cpp:1089
#1  0x00005589e2f2e8b6 in make_scripts (q=431, delta=0) at tectonic/xetex-math.c:2536
#2  0x00005589e2f30538 in mlist_to_hlist () at tectonic/xetex-math.c:2961
#3  0x00005589e2f27fdd in after_math () at tectonic/xetex-math.c:1081
#4  0x00005589e2f75555 in main_control () at tectonic/xetex-xetex0.c:17195
#5  0x00005589e2f23e47 in tt_run_engine (dump_name=0x5589e60a6880 "latex", input_file_name=0x5589e5e654b0 "infProd10Pingpong3.tex") at tectonic/xetex-ini.c:4370
#6  0x00005589e2ecbe23 in tex_simple_main (api=0x7ffdf2b9c4f8, dump_name=0x5589e60a6880 "latex", input_file_name=0x5589e5e654b0 "infProd10Pingpong3.tex") at tectonic/core-bridge.c:66
#7  0x00005589e2e219a0 in tectonic::engines::tex::TexEngine::process (self=0x7ffdf2b9c9d0, io=0x7ffdf2b9c940, events=..., status=..., format_file_name=..., input_file_name=...) at src/engines/tex.rs:133
#8  0x00005589e2de6222 in tectonic::driver::ProcessingSession::tex_pass (self=0x7ffdf2ba05b0, rerun_explanation=..., status=0x7ffdf2badfa8) at src/driver.rs:1042
#9  0x00005589e2de0e9a in tectonic::driver::ProcessingSession::default_pass (self=0x7ffdf2ba05b0, bibtex_first=false, status=0x7ffdf2badfa8) at src/driver.rs:923
#10 0x00005589e2de41d6 in tectonic::driver::ProcessingSession::run (self=0x7ffdf2ba05b0, status=0x7ffdf2badfa8) at src/driver.rs:683
#11 0x00005589e2dd3026 in tectonic::inner (args=..., config=..., status=0x7ffdf2badfa8) at src/bin/tectonic.rs:135
#12 0x00005589e2dd4593 in tectonic::main () at src/bin/tectonic.rs:293
(gdb) f
#0  0x00005589e2f7d488 in isOpenTypeMathFont (engine=0x0) at tectonic/xetex-XeTeXLayoutInterface.cpp:1089
1089	    return hb_ot_math_has_data(hb_font_get_face(engine->font->getHbFont()));
(gdb) up
#1  0x00005589e2f2e8b6 in make_scripts (q=431, delta=0) at tectonic/xetex-math.c:2536
2536	            if (((font_area[cur_f] == OTGR_FONT_FLAG) && (isOpenTypeMathFont(font_layout_engine[cur_f]))))
(gdb) p cur_f
$10 = 45
(gdb) p *font_layout_engine@cur_f
$11 = {0x0 <repeats 15 times>, 0x5589e63f6b70, 0x0, 0x5589e6216da0, 0x0 <repeats 27 times>}
```

<details><summary>valgrind logs for reference (valgrind --track-origins=yes is really slow...)</summary>

```
==24551== Memcheck, a memory error detector
==24551== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==24551== Using Valgrind-3.14.0 and LibVEX; rerun with -h for copyright info
==24551== Command: /home/mrmaxmeier/_GitRepos/_others/tectonic/target/debug/tectonic ./infProd10Pingpong3.tex
==24551== 
note: this is a BETA release; ask questions and report bugs at https://tectonic.newton.cx/
Running TeX ...
note: warnings were issued by the TeX engine; use --print and/or --keep-logs for details.
Running BibTeX ...
==24551== Use of uninitialised value of size 8
==24551==    at 0x40DEF2: scan_white_space (bibtex.c:1848)
==24551==    by 0x40E91C: eat_bib_white_space (bibtex.c:2118)
==24551==    by 0x419B8C: get_bib_command_or_entry_and_process (bibtex.c:6495)
==24551==    by 0x41A05E: bst_read_command (bibtex.c:6624)
==24551==    by 0x41B0F4: get_bst_command_and_process (bibtex.c:7002)
==24551==    by 0x41C0F5: bibtex_main (bibtex.c:7401)
==24551==    by 0x343CB7: bibtex_simple_main (core-bridge.c:103)
==24551==    by 0x339E10: tectonic::engines::bibtex::BibtexEngine::process (bibtex.rs:36)
==24551==    by 0x256BC2: tectonic::driver::ProcessingSession::bibtex_pass (driver.rs:1089)
==24551==    by 0x25881C: tectonic::driver::ProcessingSession::default_pass (driver.rs:881)
==24551==    by 0x25C1D5: tectonic::driver::ProcessingSession::run (driver.rs:683)
==24551==    by 0x24B025: tectonic::inner (tectonic.rs:135)
==24551==  Uninitialised value was created by a heap allocation
==24551==    at 0x483877F: malloc (vg_replace_malloc.c:299)
==24551==    by 0x41C2E9: xmalloc (core-memory.c:40)
==24551==    by 0x41BCED: bibtex_main (bibtex.c:7325)
==24551==    by 0x343CB7: bibtex_simple_main (core-bridge.c:103)
==24551==    by 0x339E10: tectonic::engines::bibtex::BibtexEngine::process (bibtex.rs:36)
==24551==    by 0x256BC2: tectonic::driver::ProcessingSession::bibtex_pass (driver.rs:1089)
==24551==    by 0x25881C: tectonic::driver::ProcessingSession::default_pass (driver.rs:881)
==24551==    by 0x25C1D5: tectonic::driver::ProcessingSession::run (driver.rs:683)
==24551==    by 0x24B025: tectonic::inner (tectonic.rs:135)
==24551==    by 0x24C592: tectonic::main (tectonic.rs:293)
==24551==    by 0x24FD0F: std::rt::lang_start::{{closure}} (rt.rs:64)
==24551==    by 0xFB6E02: {{closure}} (rt.rs:49)
==24551==    by 0xFB6E02: std::panicking::try::do_call (panicking.rs:294)
==24551== 
Rerunning TeX because bibtex was run ...
==24551== Conditional jump or move depends on uninitialised value(s)
==24551==    at 0x3A662D: make_scripts (xetex-math.c:2536)
==24551==    by 0x3A82D7: mlist_to_hlist (xetex-math.c:2961)
==24551==    by 0x39FD7C: after_math (xetex-math.c:1081)
==24551==    by 0x3ED2F4: main_control (xetex-xetex0.c:17195)
==24551==    by 0x39BBE6: tt_run_engine (xetex-ini.c:4370)
==24551==    by 0x343BC2: tex_simple_main (core-bridge.c:66)
==24551==    by 0x29975F: tectonic::engines::tex::TexEngine::process (tex.rs:133)
==24551==    by 0x25E221: tectonic::driver::ProcessingSession::tex_pass (driver.rs:1042)
==24551==    by 0x258E99: tectonic::driver::ProcessingSession::default_pass (driver.rs:923)
==24551==    by 0x25C1D5: tectonic::driver::ProcessingSession::run (driver.rs:683)
==24551==    by 0x24B025: tectonic::inner (tectonic.rs:135)
==24551==    by 0x24C592: tectonic::main (tectonic.rs:293)
==24551==  Uninitialised value was created by a heap allocation
==24551==    at 0x483877F: malloc (vg_replace_malloc.c:299)
==24551==    by 0x41C2E9: xmalloc (core-memory.c:40)
==24551==    by 0x39506F: load_fmt_file (xetex-ini.c:2818)
==24551==    by 0x39B288: tt_run_engine (xetex-ini.c:4259)
==24551==    by 0x343BC2: tex_simple_main (core-bridge.c:66)
==24551==    by 0x29975F: tectonic::engines::tex::TexEngine::process (tex.rs:133)
==24551==    by 0x25E221: tectonic::driver::ProcessingSession::tex_pass (driver.rs:1042)
==24551==    by 0x258E99: tectonic::driver::ProcessingSession::default_pass (driver.rs:923)
==24551==    by 0x25C1D5: tectonic::driver::ProcessingSession::run (driver.rs:683)
==24551==    by 0x24B025: tectonic::inner (tectonic.rs:135)
==24551==    by 0x24C592: tectonic::main (tectonic.rs:293)
==24551==    by 0x24FD0F: std::rt::lang_start::{{closure}} (rt.rs:64)
==24551== 
==24551== Conditional jump or move depends on uninitialised value(s)
==24551==    at 0x3A6705: make_scripts (xetex-math.c:2542)
==24551==    by 0x3A82D7: mlist_to_hlist (xetex-math.c:2961)
==24551==    by 0x39FD7C: after_math (xetex-math.c:1081)
==24551==    by 0x3ED2F4: main_control (xetex-xetex0.c:17195)
==24551==    by 0x39BBE6: tt_run_engine (xetex-ini.c:4370)
==24551==    by 0x343BC2: tex_simple_main (core-bridge.c:66)
==24551==    by 0x29975F: tectonic::engines::tex::TexEngine::process (tex.rs:133)
==24551==    by 0x25E221: tectonic::driver::ProcessingSession::tex_pass (driver.rs:1042)
==24551==    by 0x258E99: tectonic::driver::ProcessingSession::default_pass (driver.rs:923)
==24551==    by 0x25C1D5: tectonic::driver::ProcessingSession::run (driver.rs:683)
==24551==    by 0x24B025: tectonic::inner (tectonic.rs:135)
==24551==    by 0x24C592: tectonic::main (tectonic.rs:293)
==24551==  Uninitialised value was created by a heap allocation
==24551==    at 0x483877F: malloc (vg_replace_malloc.c:299)
==24551==    by 0x41C2E9: xmalloc (core-memory.c:40)
==24551==    by 0x39506F: load_fmt_file (xetex-ini.c:2818)
==24551==    by 0x39B288: tt_run_engine (xetex-ini.c:4259)
==24551==    by 0x343BC2: tex_simple_main (core-bridge.c:66)
==24551==    by 0x29975F: tectonic::engines::tex::TexEngine::process (tex.rs:133)
==24551==    by 0x25E221: tectonic::driver::ProcessingSession::tex_pass (driver.rs:1042)
==24551==    by 0x258E99: tectonic::driver::ProcessingSession::default_pass (driver.rs:923)
==24551==    by 0x25C1D5: tectonic::driver::ProcessingSession::run (driver.rs:683)
==24551==    by 0x24B025: tectonic::inner (tectonic.rs:135)
==24551==    by 0x24C592: tectonic::main (tectonic.rs:293)
==24551==    by 0x24FD0F: std::rt::lang_start::{{closure}} (rt.rs:64)
==24551== 
Rerunning TeX because "bibib.bib" changed ...
Rerunning TeX because "bibib.bib" changed ...
Rerunning TeX because "bibib.bib" changed ...
Rerunning TeX because "bibib.bib" changed ...
Rerunning TeX because "bibib.bib" changed ...
warning: TeX rerun seems needed, but stopping at 6 passes
Running xdvipdfmx ...
Writing ./infProd10Pingpong3.pdf (139626 bytes)
Skipped writing 4 intermediate files (use --keep-intermediates to keep them)
==24551== 
==24551== HEAP SUMMARY:
==24551==     in use at exit: 1,842,312 bytes in 5,821 blocks
==24551==   total heap usage: 1,213,670 allocs, 1,207,849 frees, 2,221,036,098 bytes allocated
==24551== 
==24551== LEAK SUMMARY:
==24551==    definitely lost: 158,474 bytes in 880 blocks
==24551==    indirectly lost: 295,704 bytes in 252 blocks
==24551==      possibly lost: 0 bytes in 0 blocks
==24551==    still reachable: 1,388,134 bytes in 4,689 blocks
==24551==         suppressed: 0 bytes in 0 blocks
==24551== Rerun with --leak-check=full to see details of leaked memory
==24551== 
==24551== For counts of detected and suppressed errors, rerun with: -v
==24551== ERROR SUMMARY: 13 errors from 3 contexts (suppressed: 0 from 0)

```

</details>

**Comment by pkgw** [comment]
You say "some runs" ... does that mean that this problem does not happen with consistent reproducibility? That's a little scary.

**Comment by Mrmaxmeier** [comment]
The root cause is present in every run.
Some code here probably reads from uninitialized memory and uses it to decide whether or not to dereference some pointer. I'd guess that the segfault manifests in all runs where the uninitialized memory was previously used and non-null.
