### ISSUE TITLE
0.5.1 AUR package build fails with redbox_png test suite error

### ISSUE THREAD

**Issue by roland-rollo** [tectonic-typesetting/tectonic#776]
Hi,

I tried now to upgrade tectonic to version 0.5.0 with paru (Arch Linux AUR package manager) and it throwing me this:
```
   Compiling flate2 v1.0.20
error: failed to run custom build command for `tectonic_bridge_harfbuzz v0.2.0`

Caused by:
  process didn't exit successfully: `/home/roland/.cache/paru/clone/tectonic/src/tectonic-0.5.0/target/release/build/tectonic_bridge_harfbuzz-d360d82d05dc3c96/build-script-build` (exit status: 1)
  --- stderr
  error: no such file /home/roland/.cargo/registry/src/github.com-1ecc6299db9ec823/tectonic_bridge_harfbuzz-0.2.0/harfbuzz/src/harfbuzz.cc
     if you have checked out from Git, you probably need to fetch submodules:
         git submodule update --init
     This is needed because we are attempting to compile a local copy of Harfbuzz.
warning: build failed, waiting for other jobs to finish...
error: build failed
==> ERROR: A failure occurred in build().
    Aborting...
error: failed to build 'tectonic-0.5.0-0':
```
So I thought it's AUR package error, but when I try cargo install tectonic its the same song.
```
   Compiling flate2 v1.0.20
error: failed to run custom build command for `tectonic_bridge_harfbuzz v0.2.0`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installmqIeKw/release/build/tectonic_bridge_harfbuzz-7d943ccf3c5cc12b/build-script-build` (exit status: 1)
  --- stderr
  error: no such file /home/roland/.cargo/registry/src/github.com-1ecc6299db9ec823/tectonic_bridge_harfbuzz-0.2.0/harfbuzz/src/harfbuzz.cc
     if you have checked out from Git, you probably need to fetch submodules:
         git submodule update --init
     This is needed because we are attempting to compile a local copy of Harfbuzz.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `tectonic v0.5.0`, intermediate artifacts can be found at `/tmp/cargo-installmqIeKw`

Caused by:
  build failed
```

pacman -Ss harfbuzz
```
extra/harfbuzz 2.8.1-1 [installed]
    OpenType text shaping engine
extra/harfbuzz-icu 2.8.1-1 [installed]
    OpenType text shaping engine (ICU integration)
```

**Comment by pkgw** [comment]
For the AUR package, we should probably tweak the build specification to activate the `external-harfbuzz` feature ... which won't address the underlying issue, but (as I understand it) would be the right approach and would avoid the issue.

For the `cargo install`, I guess that the way that we're preparing the crate is failing to include the vendored Harfbuzz sources. I'll have to dig into this.

Thanks for reporting promptly!

**Comment by pkgw** [comment]
Well, GitHub auto-closed this when I merged my first PR, but it turns out that I need to make one more tweak — see #778 and #781. I'll just leave this closed since I'm pretty confident that this will be solvable pretty straightforwardly.

**Comment by syntezoid** [comment]
No problem. It can be closed. If I can install it without problems, I'll let you know here.

**Comment by syntezoid** [comment]
AUR package still has problem, but new problem:
```
   Compiling tectonic v0.5.1 (/home/roland/.cache/paru/clone/tectonic/src/tectonic-0.5.1)
    Finished release [optimized] target(s) in 1m 57s
     Running unittests (target/release/deps/tectonic-b33f9df491d90079)

running 2 tests
test io::memory::tests::shrinking_file ... ok
test tests::no_segfault_after_failed_compilation ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 1.65s

     Running unittests (target/release/deps/tectonic-7c59ad2addae88cd)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/bibtex.rs (target/release/deps/bibtex-9103ec6edc9fd8d3)

running 1 test
test single_entry ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/cached_itarbundle.rs (target/release/deps/cached_itarbundle-a934e3c0c2eca3e5)

running 3 tests
test test_cached_url_provider ... ok
test test_bundle_update ... ok
test test_full_session ... ok

test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 1.18s

     Running tests/driver.rs (target/release/deps/driver-29d4a3ee82239d92)

running 1 test
test the_letter_a ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.54s

     Running tests/executable.rs (target/release/deps/executable-38f800a950744678)

running 17 tests
test bad_input_path_1 ... ok
test bad_chatter_1 ... ok
test bad_input_path_2 ... ok
test bad_outfmt_1 ... ok
test help_flag ... ok
test keep_logs_on_error ... ok
test outdir_option ... ok
test outdir_option_bad - should panic ... ok
test outdir_option_is_file - should panic ... ok
test no_color_option ... ok
test relative_include ... ok
test shell_escape ... ok
test space_in_filename ... ok
test stdin_content ... ok
test v2_new_build ... ok
test v2_new_build_multiple_outputs ... ok
test v2_new_build_open ... ok

test result: ok. 17 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 19.26s

     Running tests/formats.rs (target/release/deps/formats-05d48f262e30666e)

running 1 test
test plain_format ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.23s

     Running tests/tex-outputs.rs (target/release/deps/tex_outputs-a99b8f1248677749)

running 22 tests
test file_encoding ... ok
test a4paper ... ok
test issue393_ungetc ... ok
test md5_of_hello ... ok
test negative_roman_numeral ... ok
test no_shell_escape ... ok
test otf_basic ... ok
test pdfimages ... ok
test pdfoutput ... ok
test prim_creationdate ... ok
test prim_filedump ... ok
test prim_filemoddate ... ok
test prim_filesize ... ok
test redbox_png ... FAILED
test shell_escape ... ok
test synctex ... ok
test tectoniccodatokens_errinside ... ok
test tectoniccodatokens_noend ... ok
test tectoniccodatokens_ok ... ok
test tex_logo ... ok
test the_letter_a ... ok
test unicode_file_name ... ok

failures:

---- redbox_png stdout ----
thread 'redbox_png' panicked at 'difference in redbox_png.xdv; contents saved to disk', tests/util/mod.rs:173:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    redbox_png

test result: FAILED. 21 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 6.02s

error: test failed, to rerun pass '--test tex-outputs'
==> ERROR: A failure occurred in check().
    Aborting...
error: failed to build 'tectonic-0.5.1-1':
:: Packages failed to build: tectonic-0.5.1-1
```

**Comment by pkgw** [comment]
I'll reopen this for the `redbox_png` test suite error — that's not an issue I've seen before. Can other people reproduce it?

**Comment by syntezoid** [comment]
I want to close this issue. I tried on second computer, with clean installed Arch, and paru -S tectonic install without this problem. So it's something broken on my main computer.

**Comment by syntezoid** [comment]
Ok, so i upgrade today tectonic with paru in computer that haven't previously problem, and now he too now have this same problem
```
test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.11s

     Running tests/tex-outputs.rs (target/release/deps/tex_outputs-02e2fb563b4acfd4)

running 22 tests
test a4paper ... ok
test issue393_ungetc ... ok
test otf_basic ... ok
test md5_of_hello ... ok
test no_shell_escape ... ok
test pdfimages ... ok
test prim_filedump ... ok
test prim_filemoddate ... ok
test file_encoding ... ok
test prim_filesize ... ok
test redbox_png ... FAILED
test negative_roman_numeral ... ok
test synctex ... ok
test pdfoutput ... ok
test tectoniccodatokens_errinside ... ok
test prim_creationdate ... ok
test tectoniccodatokens_noend ... ok
test tectoniccodatokens_ok ... ok
test tex_logo ... ok
test the_letter_a ... ok
test shell_escape ... ok
test unicode_file_name ... ok

failures:

---- redbox_png stdout ----
thread 'redbox_png' panicked at 'difference in redbox_png.xdv; contents saved to disk', tests/util/mod.rs:192:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    redbox_png

test result: FAILED. 21 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 2.66s

error: test failed, to rerun pass '--test tex-outputs'
==> ERROR: A failure occurred in check().
    Aborting...
error: failed to build 'tectonic-0.6.1-1':
:: Packages failed to build: tectonic-0.6.1-1
```

**Comment by pkgw** [comment]
@syntezoid Can you give the precise OS version, CPU architecture, etc., for the system where you're seeing this?

**Comment by syntezoid** [comment]
@pkgw
uname -a
````
Arch Linux 5.12.10-arch1-1 #1 SMP PREEMPT Thu, 10 Jun 2021 16:34:50 +0000 x86_64 GNU/Linux
```

gcc -v
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/11.1.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++,d --with-isl --with-linker-hash-style=gnu --with-system-zlib --enable-__cxa_atexit --enable-cet=auto --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-gnu-indirect-function --enable-gnu-unique-object --enable-install-libiberty --enable-linker-build-id --enable-lto --enable-multilib --enable-plugin --enable-shared --enable-threads=posix --disable-libssp --disable-libstdcxx-pch --disable-libunwind-exceptions --disable-werror gdc_include_dir=/usr/include/dlang/gdc
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.1.0 (GCC)
```

lscpu
```
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         39 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  12
  On-line CPU(s) list:   0-11
Vendor ID:               GenuineIntel
  Model name:            Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    CPU family:          6
    Model:               158
    Thread(s) per core:  2
    Core(s) per socket:  6
    Socket(s):           1
    Stepping:            10
    CPU max MHz:         4600.0000
    CPU min MHz:         800.0000
    BogoMIPS:            6402.62
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscal
                         l nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulq
                         dq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_tim
                         er aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi
                          flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt inte
                         l_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d
Virtualization features:
  Virtualization:        VT-x
Caches (sum of all):
  L1d:                   192 KiB (6 instances)
  L1i:                   192 KiB (6 instances)
  L2:                    1.5 MiB (6 instances)
  L3:                    12 MiB (1 instance)
NUMA:
  NUMA node(s):          1
  NUMA node0 CPU(s):     0-11
Vulnerabilities:
  Itlb multihit:         KVM: Mitigation: VMX disabled
  L1tf:                  Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
  Mds:                   Mitigation; Clear CPU buffers; SMT vulnerable
  Meltdown:              Mitigation; PTI
  Spec store bypass:     Mitigation; Speculative Store Bypass disabled via prctl and seccomp
  Spectre v1:            Mitigation; usercopy/swapgs barriers and __user pointer sanitization
  Spectre v2:            Mitigation; Full generic retpoline, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling
  Srbds:                 Mitigation; Microcode
  Tsx async abort:       Mitigation; Clear CPU buffers; SMT vulnerable
```
rustc -V
```
rustc 1.52.1 (9bc8c42bb 2021-05-09)
```

**Comment by wisp3rwind** [comment]
I'm seeing the same issue. When running `cargo test` on master, the test succeeds, but `cargo test --release` fails. The xdv output is attached, the files differ by exactly two bytes, which are off by one compared to the expected output.

[redbox_png-outcome.zip](https://github.com/tectonic-typesetting/tectonic/files/7577078/redbox_png-outcome.zip)

**Comment by pkgw** [comment]
A similar issue popped up in the Windows CI for #845, so maybe the most recent version of the Rust compiler surfaces this issue more reliably, somehow.

**Comment by pkgw** [comment]
I may have a solution for this in #847.

**Comment by pkgw** [comment]
I believe this should be fixed.
